sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE=jernejcernelc/picshare-userservice:0.1

script:
  - mvn clean package -U
  - cd api
  - docker build -t "$DOCKER_IMAGE" ./api

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"